# Generated by Django 5.0 on 2026-05-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_assessmenttype_assessment_studentscore'),
        ('accounts', '0003_studentprofile_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='academics.schoolclass'),
        ),
    ]
