# Generated by Django 5.0 on 2026-05-13 11:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_current_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_first_name', models.CharField(max_length=150)),
                ('parent_last_name', models.CharField(max_length=150)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=17)),
                ('parent_address', models.TextField()),
                ('relationship_to_student', models.CharField(max_length=50)),
                ('employment_details', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('students_data', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
