# Generated by Django 5.0 on 2026-06-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_enrollmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='assigned_class',
        ),
    ]
