# Generated by Django 5.0 on 2026-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_teacherprofile_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.')], default='Mr', max_length=10),
        ),
    ]
