# Generated by Django 5.0 on 2026-06-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_recipie_8b48cc_idx',
            old_name='accounts_no_recipie_756ff2_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_categor_57aa2c_idx',
            old_name='accounts_no_categor_1da871_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_created_caf92d_idx',
            old_name='accounts_no_created_8ab503_idx',
        ),
    ]
