# Generated by Django 5.0 on 2026-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_enrollmentrequest_parent_user_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='completed_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='parent_documents/'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_passports/'),
        ),
    ]
