# Generated by Django 5.0 on 2026-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parentprofile_completed_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
