# Generated by Django 5.0 on 2026-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='parent_profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
