# Generated by Django 5.0 on 2026-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_schoolevent_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevent',
            name='audience',
            field=models.CharField(choices=[('all', 'All (Teachers & Parents)'), ('teachers', 'Teachers Only'), ('parents', 'Parents Only')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='organizer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
