# Generated by Django 5.0 on 2026-06-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_schoolevent_audience_schoolevent_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='remarks',
            new_name='teacher_remarks',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
