# Generated by Django 5.0 on 2026-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_remarks_reportcard_teacher_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='psychomotor',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
