# Generated by Django 5.0 on 2026-08-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_lesson_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='resumption_date',
            field=models.DateField(blank=True, help_text='School resumption date for this term', null=True),
        ),
    ]
