# Generated by Django 5.0 on 2026-09-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_term_resumption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmaterial',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term for this lesson material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_materials', to='academics.term'),
        ),
    ]
