# Generated by Django 5.0 on 2026-09-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_lessonmaterial_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentscore',
            options={'ordering': ['assessment__term__start_date', 'student__last_name', 'student__first_name']},
        ),
    ]
