# Generated by Codex on 2026-07-11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='attendance_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payroll',
            name='department',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='loans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('gateway', 'Payment Gateway')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-weekly'), ('weekly', 'Weekly'), ('contract', 'Contract-Based')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='responsibility_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('preview', 'Preview'), ('approved', 'Approved'), ('locked', 'Locked'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['year', 'month'], name='finance_pay_year_f83e48_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='finance_pay_status_95b96c_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payment_date'], name='finance_pay_payment_87a5b9_idx'),
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('updated_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.payroll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollauditlog',
            index=models.Index(fields=['action'], name='finance_pay_action_317a75_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollauditlog',
            index=models.Index(fields=['timestamp'], name='finance_pay_timesta_8472db_idx'),
        ),
    ]
