# Generated by Django 5.0 on 2026-08-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payroll_salary_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['student', 'term']},
        ),
    ]
