# Generated by Django 5.0 on 2026-09-23 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_studentfee_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='True for manually recorded payments; False for gateway payments awaiting admin review.'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes for confirmation or rejection reason.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='received_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'teacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
