# Generated by Django 5.0 on 2026-09-23 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymentrecord_confirmation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='True when an admin has explicitly rejected this gateway payment.'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
